config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  # root to: "pages#index"
  # get 'snacks/:id/edit', to: 'snacks#edit'
  # patch 'snacks/:id', to: 'snacks#update'
  # get 'snack', to: 'snacks#show'

  get 'mine', to: 'snacks#mine'
  # as: 'edit_snack'
  # resources :users do
  #   resources :snacks
  # end
  # patch 'orders/:id', to: 'orders#update', as: :update_order
  resources :orders do
    member do
      patch 'update_status'
    end
  end

  get 'order_history', to: 'orders#order_history'


  resources :snacks do
    member do
      get "add_to_cart", to: "snacks#add_to_cart"
      delete "delete", to: "snacks#destroy"
    end


    resources :order_items, only: [:create]
  end

  resources :order_items, only: [:destroy]
  get 'cart', to: 'orders#cart'
  #, as: 'edit_snack'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_items
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :snack
  belongs_to :order
end

app/models/snack.rb
class Snack < ApplicationRecord
  belongs_to :user
  has_many :order_items

  has_one_attached :photo

  def related_products
    Snack.where.not(id: id).limit(4)
  end
  
  def image_with_default
    if photo.key?
      photo.key
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :snacks
  has_many :orders

  def cart
    # if the user have cart or not
    # if yes, then we use that cart
    # if no, then create a new cart

    my_cart = orders.find_by(status: "unpaid")

    if my_cart.nil?
      Order.create(user: self)
    else
      my_cart
    end
  end

  def cart?
    cart.present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
  def create
    # find the cart
    @cart = current_user.cart
    # find the snack
    @snack = Snack.find(params[:snack_id])
    # current cart order
    # compare cart inner item
    orders = current_user.cart.order_items
    check = orders.where(snack: @snack).empty?

    if check
      @order_item = OrderItem.new(
        order: @cart,
        snack: @snack,
        snack_quantity: params[:order_item][:snack_quantity]
      )
      if @order_item.save
        redirect_to cart_path
      end

    else
      snack_quantity = params[:order_item][:snack_quantity]
      cart_quantity = orders.first.snack_quantity
      current_quantity = cart_quantity + snack_quantity.to_i
      if current_quantity <= @snack.quantity
        orders.update!(snack_quantity: current_quantity)
        redirect_to cart_path
      else
        redirect_to snack_path(@snack), alert: "Fail to add into cart. #{@snack.name} contains #{cart_quantity}pcs in cart.Hit the store limit quantity"
      end
    end
  end

  def destroy
    @order_item = OrderItem.find_by(id: params[:id])
    # raise
    if @order_item.destroy!
      redirect_to cart_path, notice: "Order item was successfully removed."
    else
      redirect_to cart_path, alert: "Failed to remove order item."
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:update_status, :show ]
  def cart
    @user = current_user
    @order_lists = []
    @total = 0
    @order = Order.where(user_id: @user.id, status: "unpaid")
    @order.each do |order|
      @order_list = OrderItem.where(order_id: order.id)
      @order_lists << @order_list
    end
  end

  def order_history
    @user = current_user
    @order_lists = []
    @total = 0
    @order = Order.where(user_id: @user.id, status: "paid").order(created_at: :desc)
    @order.each do |order|
      @order_list = OrderItem.where(order_id: order.id)
      @order_lists << @order_list
    end
  end

  def show
    @order
  end

  def update_status
    @order_lists = []
    @order_list = @order.order_items
    @order_lists << @order_list
    @order_lists.each do |items|
      item = items.first
      snack = Snack.find_by(id: item.snack_id)
      snack_store = snack.quantity
      item_quantity = item.snack_quantity
      @total = item.snack_quantity * snack.price
      if snack_store >= item_quantity
        current_store = snack_store - item_quantity
        snack.update!(quantity: current_store.to_i)
        @order.update!(status: "paid")
        redirect_to cart_path, alert: "Order status updated to paid."
      else
        redirect_to cart_path, alert: "Not enough stock, please remove Order: #{@order.id}."
      end
    end
  end

  def set_order
    @order = Order.find_by(id: params[:id])
    unless @order
      redirect_to root_path, alert: "Order not found."
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    raise
    @q = Snack.ransack(params[:q])
    @snacks = @q.result(distinct: true)
  end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  def index
    @q = Snack.ransack()
  end
end

app/controllers/snacks_controller.rb
class SnacksController < ApplicationController
  def mine
    @snacks = Snack.where(user: current_user)
  end

  def show
    @snack = Snack.find(params[:id])
    @order_item = OrderItem.new
  end

  def new
    @snack = Snack.new
  end

  def create
    @snack = Snack.new(snack_params)
    @snack.user = current_user

    if @snack.save
      redirect_to snack_path(@snack)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @snack = Snack.find(params[:id])
  end

  def update
    @snack = Snack.find(params[:id])
    @snack.update(snack_params)
    redirect_to snack_path(@snack)
  end

  def destroy
    @snack = Snack.find(params[:id])
    # raise
    if @snack.destroy!
      redirect_to mine_path, alert: "#{@snack.name} successful remove from my list"
    else
      redirect_to mine_path, alert: "Failed to remove #{@snack.name}."
    end
  end

  def add_to_cart
    @snack = Snack.find(params[:id])
    @cart = current_user.cart
    @order_item = OrderItem.new
    @query_params = { product: @snack.id }
  end

  # def get_email_username(email)
  #   email.split('@')[0]
  #   @username = get_email_username(email)
  # end

  private

  def snack_params
    params.require(:snack).permit(:name, :description, :price, :quantity, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Snackbnb</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>


    <%= yield %>
  </body>
</html>

app/views/orders/cart.html.erb
<div class="container">

<% if @order_list.nil? || @order_list.count == 0 %>

        <div class="text-center" id = center>
              <%= image_tag("https://chillydraji.files.wordpress.com/2015/08/empty_cart.jpeg", alt: "Empty Cart") %>
              <h5>Ohh!!! Your Cart is empty</h5>
              <p> Looks like you have not added anything to you cart. </p>
              <p> Go ahead & explore
              <%= link_to "SNACK", root_path, class: "fw-bolder text-decoration-none"%>!!!
              </p>
            </div>


<% else %>
  <% @order_lists.each do |lists| %>

    <% if lists.nil? %>
           <div class="text-center" id = center>
              <%= image_tag("https://chillydraji.files.wordpress.com/2015/08/empty_cart.jpeg", alt: "Empty Cart") %>
              <h5>Ohh!!! Your Cart is empty</h5>
              <p> Looks like you have not added anything to you cart. </p>
              <p> Go ahead & explore
              <%= link_to "SNACK", root_path, class: "fw-bolder text-decoration-none"%>!!!
              </p>
            </div>
    <% else %>
          <% order_id = lists.first.order_id %>
          <% order = Order.find_by(id: order_id.to_i) %>

 <div class="border border-dark m-3 p-2 rounded-5">
      <p>Order ID: <%= order.id %></p>
      <% lists.each do |list| %>
        <div class="card-product my-2">
                  <%  snacks = Snack.where(id: list.snack_id) %>
                  <% snack = snacks.first
                  name = snack.name
                  description = snack.description
                  price_per_unit = snack.price
                  total_price = list.snack_quantity * snack.price
                  @total += total_price.round(2)
                %>

            <%= cl_image_tag snack.image_with_default, alt: name, height: 80, width: 80 , class: "rounded" %>

            <div class="card-product-infos flex-grow-1">
              <h2><%= name %></h2>
              <p><%= description %></p>
            </div>
            <div class= mx-5 >
              <p><small>Price:<%= price_per_unit %>$</small></p>
              <p><small>Quantity:<%= list.snack_quantity %>pcs</small></p>
              <p><small>Total Price: <%= total_price.round(2) %>$</small></p>
            </div>
            <div>
              <p class= "text-end fs-6">
              <%= link_to "🗑️", order_item_path(list), data: {turbo_method: :delete} , class: " text-decoration-none text-end py-1 px-3 rounded-3"%>
              </p>
            </div>
        </div>
  <% end %>
</div>
        <div class="fixed-bottom-container d-flex align-items-end flex-column">
          <div class="mt-auto p-2">
            <%= @total %>$
            <%= link_to "Checkout", update_status_order_path(order), data: {turbo_method: :patch }, class: "text-decoration-none bg-primary text-white p-2 rounded-3" %>

          </div>
        </div>
    <% end %>
  <% end %>
<% end %>

</div>

app/views/orders/order_history.html.erb
<div class="container">
<% if @order_list.nil? %>
 <div class="text-center" id = center>
              <%= image_tag("https://i.pinimg.com/originals/ce/a0/0d/cea00d5472fb477c9d2bf8724fac768d.jpg", alt: "Empty History") %>
              <h5></h5>
  <% else %>
  <% @order_lists.each do |lists| %>
          <% order_id = lists.first.order_id %>
          <% order = Order.find_by(id: order_id.to_i) %>


 <div class="border border-dark m-3 p-2 rounded-5">
      <p>Order ID: <%= order.id %></p>
      <% lists.each do |list| %>
        <div class="card-product my-2">
                  <%  snacks = Snack.where(id: list.snack_id) %>
                  <% snack = snacks.first
                  name = snack.name
                  description = snack.description
                  price_per_unit = snack.price
                  total_price = list.snack_quantity * snack.price
                  @total += total_price
                %>
            <%= cl_image_tag snack.photo.key, alt: name, height: 80, width: 80 , class: "rounded" if snack.photo.attached? %>
            <div class="card-product-infos flex-grow-1">
              <h2><%= name %></h2>
              <p><%= description %></p>
            </div>
            <div class= "mx-5" >
              <p><small>Price:<%= price_per_unit %>$</small></p>
              <p><small>Quantity:<%= list.snack_quantity %>pcs</small></p>
              <p><small>Total Price: <%= total_price.round(2) %>$</small></p>
            </div>
        </div>
  <% end %>
</div>
  <% end %>

<% end %>

</div>

app/views/pages/_form.html.erb
<%= search_form_for @q do |f| %>
    <%= f.search_field :name_cont, placeholder: "Search..." %>
    <%= f.submit "Search!" %>
<% end %>

app/views/pages/home.html.erb
<div class="container">
  <div id="carouselExampleAutoplaying" class="carousel slide " data-bs-ride="carousel">
    <div class="carousel-inner object-fit-contain">
      <div class="carousel-item active object-fit-contain">
        <img src="https://auntyesthers.com/cdn/shop/files/new-webbanner-2web_1024x1024.jpg?v=1652321215" height="480" class="d-block w-100" alt="chips">
      </div>
      <div class="carousel-item object-fit-contain">
        <img src="https://www.milk-food.de/wp-content/uploads/2020/12/MILK-Nestle-KitKat-Jahrespromotion-2019-02-1920x1080.jpg" height="480" class="d-block w-100" alt="munchy">
      </div>
      <div class="carousel-item object-fit-contain">
        <img src="https://mustvisit.sg/wp-content/uploads/2020/03/NTUC-Haagen-Dazs-3-For-25-dollars-1.jpg" height="480" class="d-block w-100" alt="haagendaz">
      </div>
      <div class="carousel-item object-fit-contain">
        <img src="https://jithwa.home.blog/wp-content/uploads/2019/05/02_munchys-fb-share-1200x630-ourbrand.png?w=1024" height="480" class="d-block w-100" alt="haagendaz">
      </div>
    </div>

    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>

    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>

  </div>

  <div class="row my-2">
      <% @snacks.each do |snack| %>
      <% if snack.quantity > 0 %>
        <div class="col-6 col-md-3 mb-4" >
          <div class="bg-white rounded shadow h-100">
            <div class="d-flex">
              <div class="text-center pt-2 flex-grow-1">
                <%= cl_image_tag snack.image_with_default, alt: snack.name, height: 80, width: 80 , class: "rounded" %>
              </div>
              <%= link_to "view", snack_path(snack), class:"text-decoration-none text-lowercase me-2" %>
            </div>
            <div class="p-3 rounded-bottom d-flex flex-column">
              <strong><%= snack.name %> <span class="text-muted font-weight-normal"></span></strong>
              <small class="text-muted"><%= snack.description %></small>
              <div class="d-flex align-items-end justify-content-between pt-4">
                  <small class="flex-grow-1">$<%= snack.price %></small>
                  <small class="text-right flex-shrink-0"><%= snack.quantity %>pcs</small>
                </div>
              </div>
            </div>
        </div>
        <% end %>
      <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon p-0">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "https://i.pinimg.com/originals/7d/f1/50/7df150b1433f753eae2694c66df6346b.jpg" %>
      Snackbnb
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>


    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>


          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
          <%= link_to "", cart_path, class:"fa-solid fa-cart-shopping pt-3 mx-2 text-decoration-none nav-link text-primary" %>
          </li>
          <li class="nav-item">
          <%=  link_to "History", order_history_path , class: "nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "My Snacks", mine_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown my-auto ms-2">
            <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="fa-solid fa-user"></i>
            </a>


            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <div class="nav-item d-flex">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </div>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/snacks/_form.html.erb
  <%= simple_form_for(snack) do |f| %>
    <div class="row">
    <div class="col-6">
      <%= f.input :name %>
      <%= f.input :description %>
      <%= f.input :price %>
      <%= f.input :quantity %>
      <%= f.input :photo, as: :file %>
      <%= f.submit %>
    </div>
    <div class="col-6 ">
      <%= image_tag "https://www.sarahremmer.com/wp-content/uploads/2016/02/kid-reaching-treat.jpg", alt: "snack", height: 300, width: 300 , class: "w-100 h-100 object-fit-fill border rounded" %>
    </div>
    </div>
  <% end %>

app/views/snacks/_form_for_show.html.erb
        <%= simple_form_for [snack, order_item] do |f| %>
          <%= f.input :snack_quantity, label: false, input_html: {
            min: 1,
            max: snack.quantity,
            value: 1,
            data: { quantity_button_target:"input" },
            class: 'd-none'
          } %>
          <%= f.submit 'Add To Cart' %>
        <% end %>

app/views/snacks/_related_products.html.erb
<div class="my-5">
  <h2>Related Products</h2>
  <div class="row">
    <% snack.related_products.each do |related_snack| %>

      <div class="col-3 text-center">
        <%#= cl_image_tag related_snack.photo.key if related_snack.photo.key? %>
        <%= link_to(snack_path(related_snack), {class: "text-decoration-none"}) do %>
          <%= cl_image_tag related_snack.image_with_default, width: "100%" %>
          <%= related_snack.name %>
        <% end %>
      </div>

    <% end %>

  </div>
</div>

app/views/snacks/add_to_cart.html.erb
<div class="container mt-2">
  <h1>Order page</h1>
  <p>How many <%= @snack.name %> would you like to purchase?</p>
  <%= simple_form_for @order_item do |f| %>
    <%= f.input :snack_quantity %>
    <%= f.submit %>
  <% end %>
</div>

app/views/snacks/edit.html.erb
<div class="container">
  <h1>Edit: <%=@snack.name %></h1>
  <%= render "form", snack: @snack %>
</div>

app/views/snacks/index.html.erb
<h1>i am snacks index</h1>

app/views/snacks/mine.html.erb
<div class="container">
  <div class="d-flex justify-content-between align-items-center border-bottom py-3 mb-3">
    <div>
      <%= link_to "Back to home", root_path, class: 'btn btn-secondary' %>
    </div>
    <div class="text-center">
      <%= image_tag "https://50gram.com.my/wp-content/uploads/2022/04/50G_2029-scaled.jpg", height: 100, width: 100, class: "rounded-circle mb-2" %>
      <h4><%= current_user.email.split('@').first.capitalize %></h4>
    </div>
    <div>
      <%= link_to "+ Add New Items", new_snack_path, class: 'btn btn-primary' %>
    </div>
  </div>

  <div class="row card-snack">
      <% @snacks.each do |snack| %>
        <div class="col-6 mb-4" >
          <div class="d-flex align-items-center bg-white rounded shadow px-4 card-body">
            <div class="py-3">

              <%= cl_image_tag snack.image_with_default, alt: snack.name, height: 80, width: 80 , class: "rounded" %>

            </div>
            <div class="position-relative flex-grow-1 d-flex">
              <div class="position-absolute card-links">
                <%= link_to "Edit", edit_snack_path(snack), class:"text-decoration-none text-lowercase" %>
                <%= link_to "🗑️", delete_snack_path(snack), data: {turbo_method: :delete} , class: "text-decoration-none py-1 px-3 rounded-3"%>
              </div>
              <div class="p-3 rounded-bottom d-flex flex-grow-1 flex-column">
                <strong><%= snack.name %> <span class="text-muted font-weight-normal"></span></strong>
                <small class="text-muted flex-grow-1 block"><%= snack.description %></small>
                <div class="d-flex align-items-end justify-content-between pt-4">
                  <div>
                    $<small class="flex-grow-1"><%= snack.price %></small>
                  </div>
                  <small class="text-right flex-shrink-0"><%= snack.quantity %>pcs</small>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
  </div>


</div>

app/views/snacks/new.html.erb
<div class="container">
  <h1>Create a new snack</h1>
  <%= render "form", snack: @snack %>
</div>

app/views/snacks/show.html.erb
<div class="container mt-2">
  <div class="row">
    <div class="image_wrapper bg-white py-3 col-6">

      <%= cl_image_tag @snack.image_with_default, alt: @snack.name, height: 300, width: 300 , class: "rounded mx-auto d-block" %>

    </div>
    <div class="text_wrapper card col-6 pt-2" data-controller="quantity-button">
      <h1 class="fs-1"><strong><%= @snack.name %></strong></h1>
      <p class='fs-3'>SGD <%= @snack.price %></p>
      <p>Only <%= @snack.quantity %> remaining in stock</p>
      <div class='card py-2 mb-2 text-center rounded' style="width: 150px;">
        <div>
        <p>Order Quantity</p>
          <button type="button" data-action="quantity-button#decrement" data-quantity-button-target="minusButton" class="qty-count qty-count--minus">-</button>
          <span class="product-qty" data-quantity-button-target="label" data-min="1" data-max="<%= @snack.quantity %>">1</span>
          <button type="button" data-action="quantity-button#increment" data-quantity-button-target="addButton" class="qty-count qty-count--add">+</button>
        </div>
        <%= render 'form_for_show', snack: @snack, order_item: @order_item %>

        <%#= link_to 'Add to cart', add_to_cart_snack_path(@snack), class: "btn btn-primary" %>
        <%# <button type="button" class="btn btn-light">Add to Cart</button> %>
      </div>
      <%#= link_to 'Add to cart', add_to_cart_snack_path(@snack, @query_params), class: "b_add_to btn btn-primary" %>
      <p class='fs-5 mb-0'><strong>Description:</strong></p>
      <p><%= @snack.description %></p>
    </div>
  </div>

  <%= render 'related_products', snack: @snack %>
</div>